export const LOGS_LIST_REQUEST = "LOGS_LIST_REQUEST";
export const LOGS_LIST_SUCCESS = "LOGS_LIST_SUCCESS";
export const LOGS_LIST_FAIL = "LOGS_LIST_FAIL";

export const LOGS_UPDATE_REQUEST = "LOGS_UPDATE_REQUEST";
export const LOGS_UPDATE_SUCCESS = "LOGS_UPDATE_SUCCESS";
export const LOGS_UPDATE_FAIL = "LOGS_UPDATE_FAIL";

export const LOGS_CREATE_REQUEST = "LOGS_CREATE_REQUEST";
export const LOGS_CREATE_SUCCESS = "LOGS_CREATE_SUCCESS";
export const LOGS_CREATE_FAIL = "LOGS_CREATE_FAIL";

export const LOGS_DELETE_REQUEST = "LOGS_DELETE_REQUEST";
export const LOGS_DELETE_SUCCESS = "LOGS_DELETE_SUCCESS";
export const LOGS_DELETE_FAIL = "LOGS_DELETE_FAIL";
